num_1 = valid
1num = invalid - #Starts with a number
firstname = valid
lastname = valid
age = valid
_1 = valid
country = valid
city = valid
first_name  = valid
last_name = valid
capital_city = valid
year_2021 = valid
last-name = invalid - #Has a hyphon 
user$name = invalid - #has an invalid symbol
year2021 = valid
current_year_2021 = valid
birth_year = valid
sur@name = invalid - #has an invalid symbol